### ISSUE TITLE
Google Chrome Out of memory

### ISSUE THREAD

**Issue by sasah** [alerta/alerta-webui#162]
**Issue Summary**
Google Chrome Out of memory

**Environment**
- OS: Linux
- API version: alerta-6.8.1-py2.py3-none-any.whl alerta_server-7.2.1-py2.py3-none-any.whl
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? No

- web UI version: 7.2.0

**To Reproduce**
1. Open Google Chrome
2. Open Alerta site
3. Wait
4. Out of memory in dev tools

![image001](https://user-images.githubusercontent.com/1188384/57371958-ee65da00-719c-11e9-826b-84550a0a5f38.png)

**Expected behavior**
All work without errors.

**Comment by satterly** [comment]
Are you saying that you do nothing except login and go the the alert list summary and do not click on anything and eventually it runs out of memory? (I just want to be sure you aren't clicking around to different pages and/or clicking into the alert details page repeatedly).

And can you tell me how many alerts are being returned at every refresh? What does the counter say in the environment tab? And what is the `/alerts` payload size (you'll need to check the Network tab for this info)
