### ISSUE TITLE
Wasted space in alert list

### ISSUE THREAD

**Issue by escoand** [alerta/alerta-webui#182]
**Issue Summary**
The alert list wastes space for the description column which isn't used in my case at all...

**Environment**
- OS: Ubuntu
- API version: 7.2.7
- Deployment: Cloud Foundry
- Database: MongoDB
- Server config:
  Auth enabled? Yes
  Auth provider? OpenID
  Customer views? Yes
- web UI version: 7.2.7
- CLI version: 7.2.1

**Expected behavior**
Try to avoid wrapping lines when possible.

**Screenshots**
![issue](https://user-images.githubusercontent.com/428567/58084514-549a2600-7bbb-11e9-9b93-5d26bc93179b.png)

**Comment by satterly** [comment]
Fixed in version 7.2.9
