### ISSUE TITLE
Orange bar shows under All instead of specific environment when back from alert details

### ISSUE THREAD

**Issue by MisterCodo** [alerta/alerta-webui#184]
**Issue Summary**
The orange bar always goes under All when back from an alert's detail view, even when it should be a more specific environment. 

**Environment**
- OS: Linux
- API version: 7.2.5
- Deployment: Docker
- For self-hosted, WSGI environment: nginx/uwsgi
- Database: Postgres
- Server config:
  Auth enabled? Yes
  Auth provider? Keycloak
  Customer views? No
  (or provide the `/config` endpoint output)
- web UI version: 7.2.5
- CLI version: 6.8.1

**To Reproduce**
1. On the main Alerts page, select a specific environment like 'CustomEnvironment' to display only alerts specific to this environment
2. Click on an alert to see its details
3. Click on the back arrow to go back to main Alerts page
4. As expected, the alerts displayed in the list are only the ones from 'CustomEnvironment'. The orange bar is erroneously displayed under the All environments instead of 'CustomEnvironment'. 

**Expected behavior**
The orange bar should be displayed under the 'CustomEnvironment'.

**Additional context**
I'm using custom ALLOWED_ENVIRONMENTS.

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
Fixed in version 7.2.9
