### ISSUE TITLE
Environment tab missing after new alert

### ISSUE THREAD

**Issue by MisterCodo** [alerta/alerta-webui#187]
**Issue Summary**
The environment tabs at the top of the alerts list page do not get updated properly when new alerts appear in the list. 

**Environment**
- OS: Linux
- API version: 7.2.5
- Deployment: Docker
- For self-hosted, WSGI environment: nginx/uwsgi

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Keycloak
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: 7.2.5
- CLI version: 7.2.1

**To Reproduce**
1. Start from a fresh install of Alerta.
2. Send an alert to Alerta with environment "Development"
3. Alerta environment tabs will only display "ALL". The "Development" environment tab is missing.

**Expected behavior**
When the new alert appears in the alerts list page, the "Development" tab should also appear with a count of 1.

**Screenshots**
![MissingEnv](https://user-images.githubusercontent.com/46073244/58528430-72135500-81a4-11e9-9c76-da0bf0894504.png)

**Additional context**
Manually refreshing the page will display tabs properly:
![EnvAfterRefresh](https://user-images.githubusercontent.com/46073244/58528444-7a6b9000-81a4-11e9-84a2-fb13a423a67b.png)

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
Fixed in version 7.2.9
