### ISSUE TITLE
color_map: text color not changing

### ISSUE THREAD

**Issue by ajanwari** [alerta/alerta-webui#191]
I am using the Alerta docker image (v7.2.7) and it seems like changing the 'text' color in COLOR_MAP is not being reflected in the web ui.

Following configuration is passed for color_map:

COLOR_MAP = {
    'severity': {
        'critical':      '#cccccc',
        'major':          '#e2e2e2',
        'minor':       '#ff9980',
        'warning':       '#f7f7f7',
        'indeterminate': '#A6ACA8',
        'cleared':       '#00AA5A',
        'normal':        '#00AA5A',
        'ok':            '#00AA5A',
        'information':   '#00A1BC',
        'debug':         '#9D006D',
        'security':      '#333333',
        'unknown':       '#A6ACA8'
    },
    'text':              'white',
    'highlight':         'skyblue'
}

severity colors are working fine but the text is always BLACK.

**Comment by satterly** [comment]
Fixed in v7.2.9
