### ISSUE TITLE
Refresh Alerta Web UI using F5 returns 404 Not found

### ISSUE THREAD

**Issue by pkvel01** [alerta/alerta-webui#212]
Alerta Web version : Latest 
alerta 7.2.11
OS : Linux
Behind Nginx

We use grafana - prometheus Alert Manager to display count of alerts,we link alerta web ui url to grafana dashboard for showing critical or warning alerts 

Earlier version of web UI supported this feature i.e when i click the count of critical alerts in grafana it redirects me to alerta filtered page to show only critical alerts for a particular service. 

i upgraded web UI to 7.x and this is not working now. 

Developer Logs Shows

Failed to load resource: the server responded with a status of 404 (Not Found)

Nginx Logs 

[09/Jul/2019:18:27:26 -0700] "GET /alerts HTTP/1.1" 404 571 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36" 

Nothing on the uwsgi logs.

**Comment by d1eg0v** [comment]
I'm having the same issue.

**Comment by satterly** [comment]
See https://router.vuejs.org/guide/essentials/history-mode.html#nginx

**Comment by pkvel01** [comment]
thanks it worked,.

**Comment by satterly** [comment]
This has been asked often enough that I will add it to the FAQ page on the docs website.
