### ISSUE TITLE
UI freezes Firefox after running for several hours

### ISSUE THREAD

**Issue by stohrendorf** [alerta/alerta-webui#237]
**Issue Summary**
I have built a bridge for pulling job states from a legacy component and pushing it into alerta, which means there are always around 100 alerts with several severities present across different environments. When the UI runs for a few hours without being interacted with, Firefox tells that the page is no longer responding. The UI itself is also pretty slow when moving the mouse over the alerts. A quick performance analysis using the integrated developer tool show that a major part of the time is spent in mouseenter/mouseexit/readystatechange event handlers and DOM updates.

**Environment**
- OS: Ubuntu 16.04
- API version: 7.4.0
- Deployment: Docker

- Database: Postgres

- Server config:
```json
{
"actions": [],
"alarm_model": {
"colors": {
"severity": {
"cleared": "#00CC00",
"critical": "red",
"debug": "#9D006D",
"indeterminate": "lightblue",
"informational": "#00CC00",
"major": "orange",
"minor": "yellow",
"normal": "#00CC00",
"ok": "#00CC00",
"security": "blue",
"trace": "#7554BF",
"unknown": "silver",
"warning": "dodgerblue"
},
"text": "black"
},
"defaults": {
"normal_severity": "normal",
"previous_severity": "indeterminate",
"status": "open"
},
"name": "Alerta 7.4.0",
"severity": {
"cleared": 7,
"critical": 1,
"debug": 8,
"indeterminate": 5,
"informational": 6,
"major": 2,
"minor": 3,
"normal": 7,
"ok": 7,
"security": 0,
"trace": 9,
"unknown": 10,
"warning": 4
},
"status": {
"ack": "C",
"assign": "B",
"blackout": "E",
"closed": "F",
"expired": "G",
"open": "A",
"shelved": "D",
"unknown": "H"
}
},
"audio": {
"new": null
},
"auth_required": true,
"aws_region": "us-east-1",
"azure_tenant": "common",
"client_id": "********",
"cognito_domain": null,
"colors": {
"severity": {
"cleared": "#00CC00",
"critical": "red",
"debug": "#9D006D",
"indeterminate": "lightblue",
"informational": "#00CC00",
"major": "orange",
"minor": "yellow",
"normal": "#00CC00",
"ok": "#00CC00",
"security": "blue",
"trace": "#7554BF",
"unknown": "silver",
"warning": "dodgerblue"
},
"text": "black"
},
"columns": [
"severity",
"status",
"lastReceiveTime",
"timeoutLeft",
"duplicateCount",
"customer",
"environment",
"service",
"resource",
"event",
"value"
],
"customer_views": false,
"dates": {
"longDate": "d/M/yyyy h:mm:ss.sss a",
"mediumDate": "EEE d MMM HH:mm",
"shortTime": "HH:mm"
},
"debug": false,
"email_verification": false,
"endpoint": "http://********/api",
"github_url": "https://github.com",
"gitlab_url": "https://********",
"indicators": {
"queries": [
{
"query": [
[
"environment",
"Production"
]
],
"text": "Production"
},
{
"query": [
[
"environment",
"Development"
]
],
"text": "Development"
},
{
"query": {
"q": "event:Heartbeat"
},
"text": "Heartbeats"
},
{
"query": "group=Misc",
"text": "Misc."
}
],
"severity": [
"critical",
"major",
"minor",
"warning",
"indeterminate",
"informational"
]
},
"keycloak_realm": null,
"keycloak_url": null,
"oidc_auth_url": "https://********/oauth/authorize",
"provider": "gitlab",
"refresh_interval": 5000,
"severity": {
"cleared": 7,
"critical": 1,
"debug": 8,
"indeterminate": 5,
"informational": 6,
"major": 2,
"minor": 3,
"normal": 7,
"ok": 7,
"security": 0,
"trace": 9,
"unknown": 10,
"warning": 4
},
"signup_enabled": false,
"site_logo_url": "",
"sort_by": "lastReceiveTime",
"tracking_id": null
}
```
- web UI version: 7.4.0
- Browser: Firefox 68.0.2

**To Reproduce**
1. Show alert list, use default filters
2. Have around 100 alerts visible, with only a few updates every few minutes
3. Let it run for a few hours

**Expected behavior**
No freezes, UX should be a little better.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7853507/64020197-42704200-cb31-11e9-9441-c4328814bac4.png)

Just moving the mouse cursor over the rows for a while:
![grafik](https://user-images.githubusercontent.com/7853507/64020517-10abab00-cb32-11e9-828c-36f42d1fe866.png)

**Comment by satterly** [comment]
Are you able to test this to see if it solves your issue?

**Comment by stohrendorf** [comment]
Unfortunately I can't get to run the beta docker image properly. There are no console or network errors, it just doesn't react to any click.

**Comment by satterly** [comment]
You can just try the online version here ...
https://beta.alerta.io

**Comment by stohrendorf** [comment]
It's better now, but it's still relatively slow (you certainly notice a lag). I have added 100 alerts to the beta page so you can experience it yourself. There are still some very long `onreadystatechange` events.

**Comment by satterly** [comment]
You're going to have to be more specific than just "you certainly notice a lag" because I'm not seeing that. Can you create a screen recording of you using Firefox that demonstrates exactly what you are doing when there is noticeable lag?

And if you have any specific information about where exactly in the code base all the `onreadystatechange` events that you are observing are coming from please let me know.

**Comment by stohrendorf** [comment]
Sorry, it seems like this is a problem with the specific environment I'm working in. I can't reproduce it here at home, the only noticable lags occur when the alerts are fetched from the server, although that still seems quite slow for around 100 alerts, but that's another issue. I'm closing this one now.
