### ISSUE TITLE
Multi select range of alerts

### ISSUE THREAD

**Issue by ppruchnerovic** [alerta/alerta-webui#242]
**Is your feature request related to a problem? Please describe.**
We faced the situation where we had planned maintenance of the whole datacenter.
We needed to snooze alerts from the whole datacenter.
You can search for the alerts in Alerta Web UI, but multi-select works only one by one (and also only in Chrome) [win key] + [left mouse] which is useless if you have 500+ alerts you have to snooze.

**Describe the solution you'd like**
I would like to have the possibility to select a range of alerts, for example by selecting the first one with [win key] + [left mouse] and then the last one with [Shift] + [win key] + [left mouse].

**Describe alternatives you've considered**
Or alternatively to select all alerts on the actual screen where I limited my selection with Search/Filter.

**Workaround**
I have found a way to ack multiple alerts based on filter/query conditions using alerta cli.
```
# Search for all Open alerts from environments SIMU where event contains word deadman
alerta query -f status=open -f environment=SIMU -f event=~deadman
# Acknowledge them
alerta ack -f status=open -f environment=SIMU -f event=~deadman
```

**Comment by satterly** [comment]
If you apply a filter and that only displays the alerts you are interested in then you can just select all like this with a single click ...

![multi-select](https://user-images.githubusercontent.com/615057/64910657-f0c2dc80-d718-11e9-9b81-6ba9fa7e8041.gif)

Is that what you wanted?

**Comment by ppruchnerovic** [comment]
Ah, exactly that.

We are using Alerta 6.7 and as I haven't seen it in demo at try.alerta.io I
thought it is not implemented yet.

Thanks.

**Comment by satterly** [comment]
No problem. Thanks for reminding me that I need to update try.alerta.io -- especially as I've just archived the v6 web ui repo.
