### ISSUE TITLE
Description is shown regardless of configuration

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#250]
**Issue Summary**
Description is shown regardless of configuration. In our case it's show twice because COLUMNS is alertad.conf already contains 'text' element. But users might want to configure UI to hide description at all.

**Environment**
  - OS: Linux
  - API version: 7.4.1
  - Deployment: self-hosted
  - For self-hosted, WSGI environment: nginx/uwsgi
  - Database: MongoDB
  - Server config:
    - Auth enabled? Yes
    - Auth provider? Basic
    - Customer views? No
  - web UI version: 7.4.1
  - CLI version: 7.4.0

**To Reproduce**
1. Configure COLUMN into alertad.conf containing 'text' field.

**Expected behavior**
There shouldn't be two Description columns.

**Comment by lucasalvatore1** [comment]
Related to this, we should be able to order the "descriptions" column where ever we want.
Seems that it is always shown as the last column regardless of anything in the COLUMNS list.
