### ISSUE TITLE
Filters are not saved

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#251]
**Issue Summary**
Every ops in our environment wants to watcxh only for open alerts. At the moment they have to configure filters every time they open Alerta UI to remove acked status from filter.

**Environment**
  - OS: Linux
  - API version: 7.4.1
  - Deployment: self-hosted
  - For self-hosted, WSGI environment: nginx/uwsgi
  - Database: MongoDB
  - Server config:
    - Auth enabled? Yes
    - Auth provider? Basic
    - Customer views? No
  - web UI version: 7.4.1
  - CLI version: 7.4.0

**To Reproduce**
1. Open the UI.

Filter configuration is always the same showing open and acked alerts.

**Expected behavior**
A User should be a able to configure a default filter configuration.

**Comment by satterly** [comment]
Fixed by #264
