### ISSUE TITLE
UI complaining about missing scope read:customers

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#252]
**Issue Summary**
Viewers in our system don't have any permissions except strictly required read:alerts and read:blackouts. But a webUI complains in every load:
  "Missing required scope: read:customers (403)"

Is it really needed? Should it be documented at least?

**Environment**
  - OS: Linux
  - API version: 7.4.1
  - Deployment: self-hosted
  - For self-hosted, WSGI environment: nginx/uwsgi
  - Database: MongoDB
  - Server config:
    - Auth enabled? Yes
    - Auth provider? Basic
    - Customer views? No
  - web UI version: 7.4.1
  - CLI version: 7.4.0

**To Reproduce**
1. Configure a user having read:alerts permission only.
2. Log into web UI with this user credentials.

Alert appears in the bottom of the view: "Missing required scope: read:customers (403)"

**Comment by satterly** [comment]
The web UI will now only query for the customer list if customer views are enabled.
