### ISSUE TITLE
Support custom date/time formats

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#253]
**Is your feature request related to a problem? Please describe.**
None of preconfigured date/time formats suits into our environment. The old web UI honored DATE_FORMAT_* settings in server, but the new one doesn't. 

**Describe the solution you'd like**
Either support custom date/time format in UI or honor DATE_FORMAT_* configured in server.

**Comment by satterly** [comment]
As requested, #256 will honour `DATE_FORMAT_*`  settings in server config, such as ...

```
DATE_FORMAT_LONG_DATE = 'ddd D MMM, YYYY HH:mm:ss.SSS Z'  # eg. Tue 9 Oct, 2018 09:24:03.036 +02:00
DATE_FORMAT_MEDIUM_DATE = 'ddd D MMM HH:mm'  # eg. Tue 9 Oct 09:24
DATE_FORMAT_SHORT_TIME = 'HH:mm'  # eg. 09:24
```
