### ISSUE TITLE
Tooltips for actions in the alert view

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#255]
**Is your feature request related to a problem? Please describe.**
It's problematic at least for a new users to find out what icon initiates what action in the alert view (these small action icons in the right of every alert).   

**Describe the solution you'd like**
I think these deserve to have a tooltips.

**Comment by satterly** [comment]
I'm reluctant to add tooltips to these icons because the alert list is already very complex and there have been reports about poor performance. How long does it take for new users to work out, and remember, what the icons mean anyway? I can't imagine it's very long.
