### ISSUE TITLE
Edit user of the API key

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#258]
**Is your feature request related to a problem? Please describe.**
You can specify the user of the API key via API, but this functionality is not available in the UI. In our environment only admins create API keys and therefore their user is attached to the key which is not we want.

**Describe the solution you'd like**
Functionality to the UI to specify and edit user attached to the API keys.

**Comment by satterly** [comment]
<img width="514" alt="Screenshot 2020-01-26 at 13 58 55" src="https://user-images.githubusercontent.com/615057/73135581-0390da80-4044-11ea-83ea-28d937c8aa8c.png">

**Comment by satterly** [comment]
<img width="518" alt="Screenshot 2020-01-26 at 14 00 41" src="https://user-images.githubusercontent.com/615057/73135610-46eb4900-4044-11ea-8843-7dda518549eb.png">
