### ISSUE TITLE
Enviroment tabs order moves randomly during refresh 

### ISSUE THREAD

**Issue by pavleec** [alerta/alerta-webui#259]
**Issue Summary**
I'm using multiple enviroments and when the alert page get's refreshed they change their order with no aparent reason. The orange underline focus on active tab also get's lost. It looks like below ( checked it in Firefox and Chrome):

**Environment**
- OS: CentOS Linux 7.7
- API version: 7.4.1
- Deployment: self-hosted
- For self-hosted, WSGI environment: apache/mod_wsgi
- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes
- web UI version: 7.4.1

**To Reproduce**
1. Go to: Use any browser and sent some event from multiple enviroments
2. Click on: Any enviroment tab

**Expected behavior**
Enviroment tabs should be sorted alphabetically or by numer of active events. Active tab should keep it's focus.

**Screenshots**
![chrome-capture (1)](https://user-images.githubusercontent.com/12551929/67478003-8415f880-f65b-11e9-9774-4e70d83e542c.gif)

**Comment by satterly** [comment]
The tabs will now be sorted as "ALL" and then alphabetically.

**Comment by escoand** [comment]
The count is now not the filtered amount but the total amount of alerts. This is not realy helpful when I filtered for open alerts and the count of 699 is shown:
```json
...
{
	"2": {
		"count": 699,
		"environment": "28",
		"severityCounts": {
			"major": 30,
			"minor": 45,
			"normal": 624
		},
		"statusCounts": {
			"ack": 2,
			"blackout": 19,
			"closed": 314,
			"expired": 364
		}
	}
},
...

**Comment by satterly** [comment]
I'm pretty sure this has been fixed in later versions. If not please let me know.
