### ISSUE TITLE
WebGUI - attribute fields spacing issue

### ISSUE THREAD

**Issue by pavleec** [alerta/alerta-webui#260]
**Issue Summary**
I don't think is it intended behaviour but in event details GUI page, for every attribute field a space char is inserted between uppercase letters. For instance alerta query returns the following attributes for the event:
```
"attributes": {
            "bsnAPMacAddrTrapVariable": "0:be:75:xx:xx:xx",
            "bsnAPName": "none1",
        },
```

**Environment**
- OS: Linux
- API version: 7.4.1
- Deployment: self-hosted
- For self-hosted, WSGI environment: apache/mod_wsgi
- Database: MongoDB

- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes
- web UI version: 7.4.1
- CLI version: 7.4.0

**To Reproduce**
1. Sent sample event with attribute containing upper and lowercase letters
2. Open GUI and check event details page

**Expected behavior**
Attribute name should be properly displayed

**Screenshots**
![obraz](https://user-images.githubusercontent.com/12551929/67480383-115b4c00-f660-11e9-8948-161a4e78a38a.png)

**Comment by satterly** [comment]
This is a feature not a bug. Change the name of your attribute to `bsnApMacAddrTrapVariable` instead and it will render as ... `Bsn Ap Mac Addr Trap Variable`
