### ISSUE TITLE
Feature: Export view as csv

### ISSUE THREAD

**Issue by jadbaz** [alerta/alerta-webui#263]
**Is your feature request related to a problem? Please describe.**
We get asked for reports of errors that happen for certain filters (by resource, environment, date, etc...), the best way to have these is as csv/excel.

**Describe the solution you'd like**
An "export as csv" button that downloads a csv file of whatever is in view.

**Describe alternatives you've considered**
This could probably be done now using an API call + a few transforms

**Comment by satterly** [comment]
<img width="168" alt="Screenshot 2020-01-26 at 13 56 49" src="https://user-images.githubusercontent.com/615057/73135553-b7de3100-4043-11ea-9da5-60b9faa1bddb.png">

attributes,correlate,createTime,customer,duplicateCount,environment,event,group,href,id,lastReceiveId,lastReceiveTime,origin,previousSeverity,rawData,receiveTime,repeat,resource,service,severity,status,tags,text,timeout,trendIndication,type,updateTime,value
[object Object],,"2020-01-25T22:25:25.850Z",null,0,"Production","node_down","Misc","http://api.local.alerta.io:8080/alert/a89bb7cb-40a5-4654-b89f-369bcdbb02a5","a89bb7cb-40a5-4654-b89f-369bcdbb02a5","a89bb7cb-40a5-4654-b89f-369bcdbb02a5","2020-01-25T22:25:25.874Z","alertad/macbook.lan","indeterminate",null,"2020-01-25T22:25:25.874Z",FALSE,"web02",Core,"major","open",,"",86400,"moreSevere","exceptionAlert","2020-01-25T22:25:25.874Z",null
[object Object],,"2020-01-25T22:07:00.562Z",null,0,"Production","node_down","Misc","http://api.local.alerta.io:8080/alert/4f01a94f-316d-43d9-b905-41b91551ae9f","4f01a94f-316d-43d9-b905-41b91551ae9f","4f01a94f-316d-43d9-b905-41b91551ae9f","2020-01-25T22:07:00.593Z","alertad/macbook.lan","indeterminate",null,"2020-01-25T22:07:00.593Z",FALSE,"web01",Web,"major","open",watch:devops@alerta.io,"",86400,"moreSevere","exceptionAlert","2020-01-25T22:07:00.593Z",null
