### ISSUE TITLE
Logout reference doesn't work - error 404

### ISSUE THREAD

**Issue by AkiJ5** [alerta/alerta-webui#267]
Hello!
I installed Alerta according to manual and after authorization on webUI I can't Log Out - it's returning error 404.
![alerta](https://user-images.githubusercontent.com/36622223/72978572-65043f80-3ddf-11ea-868c-ec7585581c5e.PNG)
Help me, please, sorting out with it.

**Comment by satterly** [comment]
Which manual? A URL would be useful. Thanks.

**Comment by AkiJ5** [comment]
This one:
`http://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html`

**Comment by AkiJ5** [comment]
Hello!
Is information I provided enough?
