### ISSUE TITLE
Customizable Environments on Panel Display

### ISSUE THREAD

**Issue by dreweastep** [alerta/alerta-webui#286]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to change the environments in the panel view to customized values. We use Prod and Non-Prod, rather than Production, Development
<img width="951" alt="Capture78" src="https://user-images.githubusercontent.com/22625065/74559443-09365d80-4f2a-11ea-9bb7-dd132975f63b.PNG">

**Describe the solution you'd like**
Either a config file change in the alertad.conf, or a way to edit this in the browser

**Additional context**
Not sure if this is already possible or not.

**Comment by satterly** [comment]
Define the panels however you like using server configuration. The default are ...
```
ASI_QUERIES = [
    {'text': 'Production', 'query': [['environment', 'Production']]},
    {'text': 'Development', 'query': [['environment', 'Development']]},
    {'text': 'Heartbeats', 'query': {'q': 'event:Heartbeat'}},
    {'text': 'Misc.', 'query': 'group=Misc'},
]
```
https://github.com/alerta/alerta/blob/2a428f814612cebee162eba04872398c7affe165/alerta/settings.py#L186-L191
