### ISSUE TITLE
Text wrapping on the Description field

### ISSUE THREAD

**Issue by madan** [alerta/alerta-webui#305]
Can we look at allowing text wrapping for the description field, as description for most of the alerts tend to be relatively long not wrapping them means a huge horizontal scroll every time to read through the description before decided if this is something that needs immediate attention or not.

![image](https://user-images.githubusercontent.com/2398794/78098576-1b4a5d80-73fd-11ea-8213-84c7cd6b5dc9.png)

**Comment by WaldemarEnns** [comment]
@madan as far as i remember, the `VDataTable` component in Vuetify, does not provide a text-wrap by default. So you have to implement it manually with CSS. A text wrap will mean that some rows of the table can be bigger (more height) and some thinner (less height) - which should not be the default, IMHO.

I guess that you may have to implement it manually.
