### ISSUE TITLE
How to show or hide columns in alerta 

### ISSUE THREAD

**Issue by annu9103** [alerta/alerta-webui#316]
hi all...
Im using this code for leaning purpose.....i want to change in the sequence of column and i also want to change the view i meant according to user requirement user can select or deselect the columns ......the below is my code that i have changed in some coding.

        **<v-select
          v-model="selectedHeaders"
          :items="headers"
          label="Select Columns"
          :menu-props="{ maxHeight: '200' }"
          multiple
          outlined
          return-object
        >
          <template v-slot:selection="{ item, index }">
            <v-chip v-if="index < 2">
              <span>{{ item.text }}</span>
            </v-chip>
            <span
              v-if="index === 2"
              class="grey--text caption"
            >(+{{ selectedHeaders.length - 2 }} others)</span>
          </template>
        </v-select>
      </v-flex>
      <v-data-table
        v-model="selected"
        :headers="customHeaders"
        :items="alerts"
        :pagination.sync="pagination"
        :rows-per-page-items="pagination.rowsPerPageItems"
        class="alert-table"
        :class="[ displayDensity ]"
        :search="search"
        must-sort
        :custom-sort="customSort"
        sort-icon="arrow_drop_down"
        select-all
      > 
computed: {
 customHeader() {
      return this.$config.columns.map(c =>
        this.selectedHeaders[c] || { text: this.$options.filters.capitalize(c), value: 'attributes.' + c }
      )
      
    },
}
 created () {
    this.headers = this.$config.columns.map(s =>this.$options.filters.capitalize(s))
    this.selectedHeaders = this.headers
  },**

I have spend too much time on this problem.....hope so i will get answer soon ...thanks in advance

**Comment by satterly** [comment]
You can do this already using a configuration option called `COLUMNS`. See https://docs.alerta.io/en/latest/configuration.html#web-ui-settings

**Comment by annu9103** [comment]
but by this we can only do on back side ...is it not possible to do using GUI.......?  I meant can we do this on web page...
