### ISSUE TITLE
is it possible to select or deselect columns in web view of alerta

### ISSUE THREAD

**Issue by annu9103** [alerta/alerta-webui#317]
<v-select
      v-model="selectedHeaders"
      :items="headers"
      label="Select Columns"
      :menu-props="{ maxHeight: '200' }"
      multiple
      outlined
      return-object
    >
      <template v-slot:selection="{ item, index }">
        <v-chip v-if="index < 2">
          <span>{{ item.text }}</span>
        </v-chip>
        <span
          v-if="index === 2"
          class="grey--text caption"
        >(+{{ selectedHeaders.length - 2 }} others)</span>
      </template>
    </v-select>
  </v-flex>
  <v-data-table
    v-model="selected"
    :headers="customHeaders"
    :items="alerts"
    :pagination.sync="pagination"
    :rows-per-page-items="pagination.rowsPerPageItems"
    class="alert-table"
    :class="[ displayDensity ]"
    :search="search"
    must-sort
    :custom-sort="customSort"
    sort-icon="arrow_drop_down"
    select-all
  > 
computed: {
customHeader() {
return this.$config.columns.map(c =>
this.selectedHeaders[c] || { text: this.$options.filters.capitalize(c), value: 'attributes.' + c }
)

},
}
created () {
this.headers = this.$config.columns.map(s =>this.$options.filters.capitalize(s))
this.selectedHeaders = this.headers
}

**Comment by satterly** [comment]
This is not the right forum to ask for help. Use the chat channel for this kind of query. https://gitter.im/alerta/chat
