### ISSUE TITLE
Text column with long text requires to scroll to reach button.

### ISSUE THREAD

**Issue by michael-doubez** [alerta/alerta-webui#318]
**Issue Summary**
When text column is too big, the table expands indefinitly and buttons are no longer readily available. The user needs to scroll for all alerts.

I suspect it is a side effect of #293.

**Environment**
- OS: Linux,
- API version: 7.5.1
- Deployment: self-hosted
- WSGI environment: nginx/uwsgi, apache

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? GitHub
  Customer views? No
  (or provide the `/config` endpoint output)

- web UI version: 7.5.0
- CLI version: N/A

**To Reproduce**
1. Generate error with long "text" field
2. Generate other errors (with reasonable lenght)
3. The buttons on the right hand side are longer visible unless you scroll the window.

**Expected behavior**

Previous version had a fixed size for the text column.

**Additional context**

This is not so bad but support is using alerta to ack confirmations and it is inconvenient to open the window for that.

**Comment by michael-doubez** [comment]
Modifying the html, it is the removal of fixed-table and text-truncate that caused that

**Comment by satterly** [comment]
Yes, thanks, I'll add the `text-truncate` back.
