### ISSUE TITLE
Strip whitespace while entering data

### ISSUE THREAD

**Issue by hasso** [alerta/alerta-webui#327]
**Is your feature request related to a problem? Please describe.**
It happens time to time that our ops enters blackouts and unexpected space symbols are entered into resource/event/etc fields. It can happen very easily if you copy/paste resource names from another app or terminal for example. This makes alerts not matching blackouts, creating unnecessary alert alerts, messages etc.

**Describe the solution you'd like**
It's probably good idea to strip whitespace from the beginning and the end of the entered data in webui.

**Describe alternatives you've considered**
I don't see any real alternative.

**Comment by satterly** [comment]
Some alternatives might be to make the whitespace more visible, or to prompt the user to confirm that any leading or trailing whitespace should be discarded. 

Take into consideration also that leading and trailing whitespace is implicitly trimmed when using the CLI unless it is surrounded by quotes.

**Comment by wo250012** [comment]
We are also running into people configuring blackouts with leading/trailing spaces on resource. This has lead to more than one query for why "blackouts are not working". I think stripping leading/trailing whitespace would be good for this.
