### ISSUE TITLE
Provide a filter toggle in blackout rules to show only active rules

### ISSUE THREAD

**Issue by nickmy9729** [alerta/alerta-webui#333]
When browsing blackout rules, there are times when there are multiple blackout rules that have expired and it is difficult to see the "active" rules.  It would be great if there was filter capability on that page to at a minimum filter by active / expired.  It could be extended to filter by other attributes such as env etc.

**Comment by satterly** [comment]
I've added filter buttons, similar to the Heartbeat list. You can already filter on other attributes (such as environment) using the text search.
