### ISSUE TITLE
Environment summary row is affected by PAGE_SIZE and does not show correct values.

### ISSUE THREAD

**Issue by Exceptionfault** [alerta/alerta-webui#336]
**Issue Summary**
When having lot's of active alerts, the performance of the UI, especially initial load or reload can take > 5 sec. Also the request between nginx and uwsgi often timed out and we get back 502 or 504 errors if multiple users are actively using the UI. (We're using the official docker image - tweaks or hints for improving nginx/uwsgi settings are appreciated :-) )

To counter that, we've reduced the refresh interval to 60s
`AUTO_REFRESH_INTERVAL = 60000` 
and reduced the number of returned records to 200
`DEFAULT_PAGE_SIZE = 200`

However, the page_size property also affects the countings on the header row, making the alert numbers for each environment wrong. 

![image](https://user-images.githubusercontent.com/1003878/84868101-78f55a00-b07c-11ea-8aa9-a2fcaa509afe.png)
vs.
`db.getCollection('alerts').count({environment: 'prod'}) = 35`

Expectation was, that the PAGE_SIZE parameter reduces the batch data prefetched by the UI, but does not affect global statistics and summaries. 
Currently, alerts for PROD environment are not shown in the UI or shown more or less randomly.

**Environment**
OS: Debian GNU/Linux 10 (buster)
API version: 
- alerta 7.5.5
- alerta client 7.5.1
- requests 2.21.0
- click 7.1.2

Deployment: OpenShift 3.11

Database: MongoDB server version: 3.6.3

Server config:
Auth enabled? No
Auth provider? Basic
Customer views? No

web UI version: 7.5.1

**To Reproduce**
Set parameter `DEFAULT_PAGE_SIZE` lower then number of alerts in DB. 
Validate shown number of alerts in the header row vs. count of alers in the database.

**Expected behavior**
Header / Summary row should show correct number of alerts - even if they are not fully loaded in the UI.

**Comment by satterly** [comment]
This is how it used to work and I was asked to change it. https://github.com/alerta/alerta-webui/issues/259#issuecomment-584078906

**Comment by satterly** [comment]
> Header / Summary row should show correct number of alerts - even if they are not fully loaded in the UI.

What happens when you apply a local filter? What should happen to the count then?

**Comment by Exceptionfault** [comment]
Well, I think those two requirements will work in parallel. 
I also think, that the top numbers should respect local filters and only show total counts based on filtered status or service or whatever is used as a filter. 
However if the resulting count for all or a certain environment is still >= `DEFAULT_PAGE_SIZE`, the numbers shown in the header must not be limited by DEFAULT_PAGE_SIZE. 

In my example above, we're using the default filters "status in (open, ack)" which are more then 800 alerts. So ideally the header will show "total 800" based on the filter, but only load 200 alerts in the ui for performace reasons.

In the best case, the ui will do a lazy pagination and load more alerts on demand when someone reaches the end of the list, but practically one would better refine the filters until the results are as granular as necessary. 

This might introduce new challenges, for example if someone changes local sorting from latest to oldest events, which would either require a new reload from the server or just filter the local list with a notification that not all events are shown. I'd always prefer the fast UI.

Also, if the UI is able to reduce the number of detailed fetched data while still showing the correct sum in the header, we would be able to use one browser instance as central dashboard in the operations room which only fetches the top 20 alerts but with very high refresh rate. 
Right now we had to reduce the fetch rate to > 60sec due to the high high volume each reload means.

**Comment by satterly** [comment]
I've looked into this in detail and agree that the current behaviour is sub-optimal at best and in the worst case actually misleading.

Alerts are returned by the API sorted by last receive time, Nd then sorted in the web UI by severity and last receive time. This means old, high severity alerts will not be displayed if they are older than the page size limit. This is not so obvious when the page size is large, but when small can lead to what seems like random alerts appearing and disappearing depending on how often they are updated.

**Comment by satterly** [comment]
This was fixed by switching to server-side sort. Available in version 8.0.0.
