### ISSUE TITLE
Erro install Alerta-webui in the Centos 7

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [alerta/alerta-webui#364]
** Summary of the problem **
Please, give me a tutorial on how to install Alert-webui on CentOS, I tried everything to install Alert-webui on centos 7 and I couldn't, I'm trying to install it on I can't days.
I tested these links below and to no avail
** problems **
I don't know how to create the /etc/uwsgi.ini and /etc/systemd/system/uwsgi.service files, I need a detailed tutorial to install the Alert, PLEASE.

https://www.digitalocean.com/community/tutorials/how-to-monitor-zabbix-alerts-with-alerta-on-centos-7

https://docs.alerta.io/en/latest/gettingstarted/tutorial-1-deploy-alerta.html#step-2-configuration

**Environment**
- OS: [e.g. Linux, Mac, Windows]
- Deployment: [Self-hosted]
- WSGI environment: [nginx / uwsgi]

- Database: [MongoDB]

- Server configuration:
   Location Nginx /usr/share/nginx/html;
   Authentication enabled? No
   Authentication provider? No
   Customer reviews? No

- web user interface version: [7]
![Screenshot from 2020-07-13 01-04-01](https://user-images.githubusercontent.com/21109538/87270142-a8458e00-c4a5-11ea-8054-2316b32a40fb.png)
![Screenshot from 2020-07-13 01-06-02](https://user-images.githubusercontent.com/21109538/87270159-b1cef600-c4a5-11ea-942d-5950d6b1101d.png)
![Screenshot from 2020-07-13 01-07-26](https://user-images.githubusercontent.com/21109538/87270166-ba273100-c4a5-11ea-8a29-a10cb99ae293.png)

**Comment by satterly** [comment]
Check out this repo https://github.com/alerta/vagrant-try-alerta

If you use `vagrant` you can just run ...

    $ vagrant up alerta-centos7

If not you can check out all the scripts that create the config ...

https://github.com/alerta/vagrant-try-alerta/tree/master/scripts/centos

I'll close this issue but if you need more help just ask. Thanks.
