### ISSUE TITLE
Usage on mobile android/iphone/etc ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [alerta/alerta-webui#365]
Is this Web-UI - meant to handle getting alerts to users ?

I would f.ex. think it nice if I could just have user open this in browser - and then it'll do push notifications (which user can f.ex. set to high priority - overriding silence if they like) ?

Or would one need to wrap this Web-UI in some "browser-appify" - to get notifications that actually ensures alerts is checked for and the mobile pings ?

(for those users who do not want mattermost etc. on their phones)

I use aNag android app today (for icinga) - but would like to replace this with Alerta.. But I need to figure out how to make sure mobile notifies - also in silent mode f.ex. (which can be done when its using the notifications framework on android/iphone)

**Comment by satterly** [comment]
> Is this Web-UI - meant to handle getting alerts to users ?

No. Use a dedicated notification service.
