### ISSUE TITLE
Google Auth - Not receiving admin role

### ISSUE THREAD

**Issue by Yentel** [alerta/alerta-webui#366]
**Issue Summary**

**Environment**
- OS: Linux
- API version: 8.0.2
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? Google
  Customer views? No

- web UI version: 8.0.0

**To Reproduce**
1. Enable google auth
2. Login using google account
3. Switch back to basic auth
4. Give the google account used in step 2 the admin role
5. Switch back to google auth
6. Login using google
7. Click profile (top right), notice the scope admin,write,read. But, no role "admin".
![image](https://user-images.githubusercontent.com/2759287/89297961-f85adf00-d664-11ea-9330-32ed4365017a.png)
8. Menu Users, edit user (myself). Note that the role admin has been assigned.
![image](https://user-images.githubusercontent.com/2759287/89297786-bcc01500-d664-11ea-90b9-4819a203ed0d.png)
9. Menus like groups ect are not showing up.
10. Switching back to basic auth, role admin shows up
![image](https://user-images.githubusercontent.com/2759287/89298427-a1093e80-d665-11ea-9987-b5e018285b78.png)

For web app issues, include any web browser JavaScript console errors.
No console errors

**Expected behavior**
Full admin permissions (admin role)

**Screenshots**

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment]
You shouldn't switch auth providers. You should either use Google auth or Basic auth, not both. To give a Google auth user admin privileges just add the email address to the `ADMIN_USERS` server setting. See https://docs.alerta.io/en/latest/configuration.html#authentication-settings
