### ISSUE TITLE
alerta-webui - nagios => send acknowledgment to nagios

### ISSUE THREAD

**Issue by garnesh82** [alerta/alerta-webui#368]
hi there, 

Is there a way that i can acknowledge the alert in webui at the same time acknowledge the alert in nagios?

**Comment by satterly** [comment]
Yes, you can if Nagios can receive a webhook or can receive actions some other way. See this plugin for example which does exactly what you want but for Zabbix https://github.com/alerta/alerta-contrib/tree/master/plugins/zabbix
