### ISSUE TITLE
ALERTA-WEBUI

### ISSUE THREAD

**Issue by garnesh82** [alerta/alerta-webui#370]
Webui getting error "Undefined" after inactive browser after sometime.

Is there web-ui session timeout configured. 

OS: Debian 9

**Comment by LaurianoElmiroDuarte** [comment]
explain better what you are doing.

**Comment by satterly** [comment]
> Is there web-ui session timeout configured.

No.

**Comment by satterly** [comment]
When creating an issue you should be provided with boilerplate for the ticket. This is important for myself and others to properly address your issue. Please reopen this with the required information, thank you.
