### ISSUE TITLE
variable (sliding) column width / configurable max text length 

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta-webui#371]
**Is your feature request related to a problem? Please describe.**
We have some alerts with a large amount of text. This throws off the display since all of the text is displayed.

**Describe the solution you'd like**
It would be great to have both:
-A max column length configuration that would truncate text after a configurable length (with "...")
-The ability to dynamically slide columns to display more/less text. (I am not sure what is available in vue.js for this)

**Comment by satterly** [comment]
Yes, this is limited by the functionality provided by vue.js. I'd need to take a closer look to see if being able to dynamically adjust columns was possible.

**Comment by satterly** [comment]
Vuetify doesn't support adjustable column widths. See https://vuetifyjs.com/en/components/data-tables/

**Comment by wo250012** [comment]
Thanks for looking into that, @satterly. 
In that case, I think having a max column length setting would keep the UI from getting out of whack when a long value comes in.

**Comment by satterly** [comment]
Yes. that is possible. Working on that next.

**Comment by wo250012** [comment]
Thanks @satterly,
I noticed this was just for the text (description) field. Any chance this could be done for the value field as well? This is where we have run into longer text strings. A lot of our alerts do not have a numeric value that we track separately so we use this field as the generic text of the alert.
