### ISSUE TITLE
Notification sound settings don't save

### ISSUE THREAD

**Issue by carlnrtn** [alerta/alerta-webui#374]
Hi,

I just recently installed Alerta and I am very impressed! Lovely interface and does just what I need. I have picked up on a kind of bug though. I spent ages trying to work out why it wasnt making notification sounds for me. Turns out, it was a simple as the setting not saving. When you click the tick box, it doesn't actually enable.

I figured this out later on when I changed the font and it popped up "settings saved" and all of a sudden it started making sounds. 

Another small suggestion as well, the ability to be able to modify sound rules? I know you can acknowledge to silence, but an option to only play when the alarm originates would be nice. 

Thanks for your work!

**Comment by satterly** [comment]
Hi, I can't reproduce this error. It looks like it saves to me ...

```
{
  "attributes": {
    "prefs": {
      "displayDensity": "compact", 
      "isDark": true, 
      "isMute": false
    }
  }, 
  "status": "ok", 
  "total": 1
}
```
If you can reliably reproduce this error reopen the issue. Thanks.
