### ISSUE TITLE
double "action lists" at top of page after multiple alert selection

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta-webui#375]
**Issue Summary**
If you check multiple alerts and then click on an alert it goes to the alert details screen with the multiple alerts still selected. This has led some users to think they can add notes, etc for the multiple selected alerts.

**To Reproduce**
1. select multiple alerts via checkboxes
2. Click on a single alert
3. notice two "action lists" at top of page (see image for details)

![image](https://user-images.githubusercontent.com/54080089/96038514-16d71680-0e1c-11eb-8782-e6caed4e0b42.png)

**Comment by satterly** [comment]
I see. Thanks. This *could* be a reasonable UX for how adding notes to multiple alerts at once *might* work.
