### ISSUE TITLE
TypeError: "this.$store.getters['alerts/alerts'] is undefined"

### ISSUE THREAD

**Issue by pedro7x** [alerta/alerta-webui#381]
**Issue Summary**
Intermittent failure to display alarms on the alerts page. The alarm counters of the enviroments work correctly.

Closing the browser, clearing the cache and reopening the page usually solves the problem.

The following error message appears on the browser console:

```
TypeError: "this.$store.getters['alerts/alerts'] is undefined"
    alerts Alerts.vue:227
    VueJS 3
    alertsByEnvironment Alerts.vue:251
    VueJS 3
    ne Alerts.vue:1
    He VueJS
    ne Alerts.vue:1
    VueJS 7
    s es6.promise.js:75
    E es6.promise.js:92
    c _microtask.js:18
vue.runtime.esm.js:1888:12
```

**Environment**
- OS: Linux and Windows
- Browser: Firefox 82 and older versions too
- API version: 8.0.3
- Deployment: Alert + Alert-webui
- For self-hosted, WSGI environment: nginx/uwsgi
- Database: MongoDB
- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes
- web UI version: 8.0.1

**To Reproduce**
Wait some time after login on Alert-webui. It doesn't always happen.

It seems to me to occur more often when there are a lot of alarms.

**Screenshots**
![Alerta_erro](https://user-images.githubusercontent.com/16904031/97714437-ec35c080-1a9f-11eb-867e-bfdcbd7942d5.png)

**Comment by satterly** [comment]
I can't get this to fail for me. I'll keep an eye out for this error in future but for now I'll have to close this as it can't be reproduced.

**Comment by satterly** [comment]
Note: related to `alertsByEnvironment` somehow.

**Comment by pedro7x** [comment]
@satterly 

I found out that the problem was related to excessive memory usage.

The reason for this usage was the size of the alarm history (it was set to 200). When reducing the maximum history size (to 50) the problem stopped occurring.

One suggestion, if possible, would be to have an alarm search option in the API that does not return the history. This way, this type of search could be used in the alarm list window. Since this window does not use historical information, I believe there would be no losses but rather performance gains.

In this case, historical information would only be obtained when we enter the alarm detail screen.

In any case, I thank you for your help and I apologize for the long delay in responding to this case.
