### ISSUE TITLE
Feature Request: Customisation of Reports

### ISSUE THREAD

**Issue by gabricar** [alerta/alerta-webui#387]
1 - Add the ability to email the reports
2 - customizable reports. today we only have TOP 10, will be nice to have more filters like:
TOP xx
by Site
by date (range)
by severity

**Comment by dakotacody** [comment]
This also relates to a conversation I had in the Alerta help slack channel.
https://alerta.slack.com/archives/C01FJRJR2F2/p1617822772085800 

Our use case would be to be able to generate/view reports based off of attributes or groups etc.. 

Basically, we have alerts generated that are team specific (Database, Networking, product etc.)  Adding the ability to run a top ten report per team would allow Database to see which alerts are most common for only their team etc..  

Adding the ability to generate a report based off of a team attribute ( or any attribute, or maybe tag)  would be useful for us.
