### ISSUE TITLE
Allow per-user customization of alert colors

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta-webui#413]
I have had a lot of back and forth with users about the best color red for alerts. We seem to be in agreement (for now) but having the option for a user to choose their own colors on the settings page would be a great enhancement, I think.

**Comment by satterly** [comment]
I think it would be a mistake to allow users to choose their own colours for each severity. You would loose the ability to quickly look at a console and know what severities were active and which were the highest priority. So no, I think as difficult as it might be, getting agreement on the severity colours is really important.
