### ISSUE TITLE
Hyperlinks are almost unreadable in dark mode (v8.3.0+)

### ISSUE THREAD

**Issue by psyhomb** [alerta/alerta-webui#421]
<img width="1440" alt="Screenshot 2020-12-14 at 14 22 34" src="https://user-images.githubusercontent.com/1824874/102086575-90898180-3e18-11eb-959c-dbe6f241d9f4.png">

**Comment by satterly** [comment]
See https://github.com/vuetifyjs/vuetify/issues/1745

**Comment by psyhomb** [comment]
You also don't use consistent link coloring, please see Url and More Info links at end of the screenshot.

**Comment by psyhomb** [comment]
Thank you for fixing it.
