### ISSUE TITLE
editing link color in dark mode

### ISSUE THREAD

**Issue by wo250012** [alerta/alerta-webui#423]
This may need to be a request for a more generic way to edit CSS values in the UI but I am getting lots of requests to change the link color in dark mode to some thing more readable:

![image](https://user-images.githubusercontent.com/54080089/102251950-52dd3500-3eba-11eb-8567-734501e310b6.png)

There may be a way to edit this already but I could not find where.

**Comment by satterly** [comment]
Duplicate of #421 Fixed by #422

**Comment by wo250012** [comment]
DOH! sorry...missed that this was already closed.
