### ISSUE TITLE
Abnormally high memory usage

### ISSUE THREAD

**Issue by RylandCai** [alerta/alerta-webui#426]
Hi.

**Issue Summary**
Abnormally high memory usage.

**Environment**
- OS: Windows & Mac
- API version: alerta v8.0.3, alerta-webui v8.0.1
- Deployment: Local test, Pycharm, VSCode

- Database: MongoDB

- Server config:
  Auth enabled? No
  Customer views? No

- web UI version: v8.0.1
- CLI version: v8.0.3

**To Reproduce**
1. Send about 30 alerts by Postman.
2. high JS memory usage and slow GC happens, even the animation is a little bit slow when changing tabs.

**Expected behavior**
Better performance.

**Screenshots**
![1](https://user-images.githubusercontent.com/22949352/103325755-2e6f8400-4a88-11eb-93d6-62c2e97ae0b4.png)
![2](https://user-images.githubusercontent.com/22949352/103325761-316a7480-4a88-11eb-9ec8-6f547c9c7180.png)

**Additional context**
https://github.com/alerta/alerta-webui/issues/162
Looks like this bug. Is it fixed?

**Comment by RylandCai** [comment]
And here I think is strange.
Alerts.vue, line 394:
```
refreshAlerts() {
      this.getEnvironments()
      this.getAlerts()
        .then(() => {
          this.isNewOpenAlerts && this.playSound()
          this.timer = setTimeout(() => this.refreshAlerts(), this.refreshInterval)
        })
 }
```
alert.service.ts, line 40:
```
getAlerts(query: object) {
    if (query && queryInProgress) {
      queryInProgress.cancel('Too many search requests. Cancelling current query.')
    }
    queryInProgress = axios.CancelToken.source()
    let config = {
      params: query,
      cancelToken: queryInProgress.token
    }
    return api.get('/alerts', config)
}
```

If I stayed at the list page and do nothing, the interval will call getAlerts again, `query && queryInProgress` will be true.
Seems this request should be cancelled, but it still be sended to backend.

**Comment by satterly** [comment]
There were some performance improvements recently. Can you run the latest version (v8.3.1) and let me know if you see the same issues?

**Comment by RylandCai** [comment]
Hi Satterly.
Thanks a lot for your help, the performance has improved after #430 and #431.

And I guess the list filter can also be lazy loaded.
Please check my pull request.

**Comment by satterly** [comment]
Thanks I'll take a look at your PR. Did you test master? ie. including #433?
