### ISSUE TITLE
Overall performance of alert list

### ISSUE THREAD

**Issue by escoand** [alerta/alerta-webui#429]
I really don't wanna bug you and you already invested much time in optimizing, but we're currently at a point where we have to think about moving to something different. We just migrated a third of our environments but for the operators the performance is already now nearly unusable. The backend evolved quiet well and also a list of 100 alerts just takes 0.5s from request to finish response to the client. But displaying this list takes in this specific case more than 15s and hundreds of megabytes are used for this. I'm not an expert but for me this seems to be deeply rooted in vue.js or in the usage of it.

Here is a test with Microsoft Edge Chromium - the results with Firefox are similar.

1. showing a list with 0 alerts
2. start the profiling
3. switch to an environment with 0 alerts --> ~1s
4. switch to an environment with 10 alerts --> ~2s
5. switch to an environment with 22 alerts --> ~3s
6. switch to a list limited to 100 alerts --> ~16s
7. switch to an environment with 0 alerts --> ~4.5s
8. stop profiling

![image](https://user-images.githubusercontent.com/428567/103534203-bd1c4080-4e8e-11eb-8047-f086c7af1020.png)

The values in the middle are all quiet high for 132 alerts: 650 MB = 4.9 MB each; 500,000 nodes = 3,700 nodes each.
As you can see at the bottom of the image, rendering and painting is only a small part of the cpu time.

**Comment by satterly** [comment]
Are you able to test `master` branch to see if #430 fixed your issue?

**Comment by escoand** [comment]
Is there a way to test this PR with docker?

**Comment by escoand** [comment]
> Is there a way to test this PR with docker?

Could you maybe create a docker image on every commit and add `beta` or `dev` tag? Could be complicated because of the repository separation...

**Comment by satterly** [comment]
The following PRs have hopefully addressed this issue for now, however there is probably more that could be done ... #430, #431, #432, #433, #436, #438, and #439.

**Comment by escoand** [comment]
@satterly I'm pretty impressed by your fast response and multiple fixes. Thanks for all you work.

**Comment by satterly** [comment]
A new Docker image for version 8.3.2, with web UI 8.4.0, is available now.

**Comment by escoand** [comment]
The direct comparison between 8.3.3 and 8.4.0 seems like magic. Working with Alerta is now fun again. This is great!

One small thing: When switching from env A to ALL and then to an env B, you will see again the alerts of env A before the data of B was loaded. Seems you are handling ALL separately but all other envs in one tab.

**Comment by escoand** [comment]
Hmm, this is only visible in Firefox - maybe the rendering of the tab with the loading message is delayed in FF.

**Comment by satterly** [comment]
Ok thanks. Will take a look.
