### ISSUE TITLE
Alerta ignoring custom value column width on refresh

### ISSUE THREAD

**Issue by 3IMOH** [alerta/alerta-webui#445]
**Issue Summary**
If a user sets a custom column width for value and then manually refreshes the browser that setting is lost. Clicking on settings and then going back to the alerts page "fixes" this.

**To Reproduce**
1) set a custom value width in settings
2) verify it works
3) refresh the browser
4) value column is back to default

I am using Chrome for this test

**Comment by lrusak** [comment]
I can confirm this issue with version 8.4.0

**Comment by satterly** [comment]
Should be fixed in next version 8.5.1
