### ISSUE TITLE
Alerts stay on Loading..., but all UI works correctly

### ISSUE THREAD

**Issue by wperw** [alerta/alerta-webui#454]
Hi, I've succesfully installed Alerta on a CentOS7 with PostgreSQL and ngnix.
API run perfect on port 81, and for now, until I've not all set-up correctly things run on HTTP.
When ai acces to the Alerta web UI on port 81, the same of the /api I can see alerts coming in the top panel, but nothing on the list
![image](https://user-images.githubusercontent.com/18013904/107492335-9be4f900-6b8c-11eb-93c2-2147f16653b8.png)
If I use the CLI I can correctliy see the alerts.
Another strange thing is under Report, I can see alerts and open it.
![image](https://user-images.githubusercontent.com/18013904/107492711-0d24ac00-6b8d-11eb-8e52-0dd0bedfad00.png)
I'm traiinfg for 2 days to resolve the problem, but nothing work.

The only error I've find is this on the Alert page
![image](https://user-images.githubusercontent.com/18013904/107493104-8de3a800-6b8d-11eb-8b67-6e32270c4dc1.png)

This is the About page
![image](https://user-images.githubusercontent.com/18013904/107493039-71e00680-6b8d-11eb-89a9-729ed83581d9.png)

Can anyone help me with this strange issue

**Comment by satterly** [comment]
Please upgrade to a more recent version of the web UI. This version is very old and there is a good chance the error you are seeing is already fixed.
