### ISSUE TITLE
show alarms in unduplicate format

### ISSUE THREAD

**Issue by robinlem** [alerta/alerta-webui#455]
**Is your feature request related to a problem? Please describe.**
Is it possible to display alarms without alerta grouping them. For example if I have an alarm but 1 tag changes. Then the alarm is considered as duplicated.
I use alerta with alertmanager/prometheus, and alertmanager already does the job of grouping the alarms. I would like to know if it is possible to have an option to configure alerta not to have duplicate alarms.

**Describe the solution you'd like**
have a configuration option that allows not duplicating alarms (not by default)

**Describe alternatives you've considered**
There is no alternative now.

**Additional context**
![image](https://user-images.githubusercontent.com/45788627/108509449-88890a80-72bd-11eb-95ab-7c5738a5e403.png)

**Comment by satterly** [comment]
Please review your prometheus configuration according to this [README](https://github.com/alerta/prometheus-config) and that you understand how Alerta [de-duplicates and correlates alerts](https://docs.alerta.io/en/latest/gettingstarted/tutorial-4-alerts.html#tutorial-4).
