### ISSUE TITLE
Alerta Web UI doesn't sort correctly by severity.

### ISSUE THREAD

**Issue by Sr795** [alerta/alerta-webui#457]
**Issue Summary**
When using the Alerta Web UI to sort alerts, I can sort successfully by all the available fields except severity, which produces an unexpected sorting.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 8.4.1]
- Deployment: [Azure]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. CosmosDB ]

- Server config:
  Auth enabled? Yes
  Auth provider? Azure
  Customer views? No

- web UI version: [eg. 8.4.1]
- CLI version: [eg. 8.4.1]

**To Reproduce**
Send some alerts to Alerta with varied severity levels and try sorting from the web UI.

**Expected behaviour**
Alerts of the same severities at least clump together, preferably in some order of low to high severity or vice versa.

**Screenshots**
There are 2 orderings that consistently appear when I try to order corresponding likely to sort by most severe or least severe. This consistent response is in line with sorting by other fields, so I'm pretty sure some attempt at sorting is taking place. The problem is the sorting is unexpected.

Here is one of the 2 orderings that appear when I click on the severity header circled in the image below.
![image](https://user-images.githubusercontent.com/80048026/109972038-c8ed7d00-7cee-11eb-8188-af7ace41bd81.png)

Here is the other ordering, when I click again
![image](https://user-images.githubusercontent.com/80048026/109972275-0520dd80-7cef-11eb-8034-9f74aa698fa3.png)

Any help on this would be greatly appreciated.

**Comment by satterly** [comment]
Are you using custom severities? If so please include the server config.

**Comment by Sr795** [comment]
Thank you very much for the reply. I don't believe I am using a custom severity. The severity values used have been from the below table:
![image](https://user-images.githubusercontent.com/80048026/110119217-6ad69d80-7db3-11eb-9653-a92a16a8c7c8.png)

Below is an example rule I have been using in thanos ruler which pushes alerts to alertmanager which in turn pushes to alerta
![image](https://user-images.githubusercontent.com/80048026/110119316-9194d400-7db3-11eb-8996-4fe3be22a001.png)
As you can see I have defined severity to be critical which is in the standard set of severity values.

With regards to my server config, I could not find /etc/alertad.conf but I did find /app/alertad.conf . Below are the contents:
```DATABASE_NAME = 'test'
DATABASE_RAISE_ON_ERROR = False
DATABASE_URL = <the url for the database I am using> ```

Please let me know if there are any other details that would be helpful

**Comment by satterly** [comment]
This could be an issue with CosmoDB. Can you test the same setup but with MongoDB and see if you get the same error?

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Slack](https://slack.alerta.dev).
