### ISSUE TITLE
Enable customization of openid "scope" attribute

### ISSUE THREAD

**Issue by djotanov** [alerta/alerta-webui#477]
When using openid auth mechanism, there is no way to extract roles from openid token, because scope is hardcoded to "openid+profile+email". I would need to add "groups" to scope in order to extract roles from my oidc token (I'm using Dex Idp).
I need this so I could then use ADMIN_ROLES to distinguish between regular users and admins.

Ideally, it would be good to have OIDC_SCOPE property where we could override this.

**Comment by satterly** [comment]
Dex added a [`userinfo` endpoint](https://github.com/dexidp/dex/pull/1473) for this. Can you check to see if `groups` are returned in that response?

**Comment by 3IMOH** [comment]
Closing for now...reopen if you have more information.
