### ISSUE TITLE
Configure "Show Panel"

### ISSUE THREAD

**Issue by skwalig** [alerta/alerta-webui#478]
The 'Panel' component refers to 'Production' and 'Development' environment even if we don't use them.
![image](https://user-images.githubusercontent.com/31893141/126796152-90c761dd-4f23-47c1-b2d2-9a65a272b42a.png)

- Can this panel use environment defined with the 'ALLOWED_ENVIRONMENT' property in the configuration file if the property is used?

- Can the availability of the 'Show/Hide Panel ' button be configured with a property or a specific permission ?

![image](https://user-images.githubusercontent.com/31893141/126796382-a19aa2bd-160a-4bc6-868b-6561eb07a839.png)

Regards

**Comment by 3IMOH** [comment]
With regards to your first question...you can configure the ASI panel to show/hide whatever you want:
https://docs.alerta.io/en/latest/configuration.html#alert-status-indicator-settings

I don't believe there are permissions on this UI element.

**Comment by skwalig** [comment]
Thanks for your reply
