### ISSUE TITLE
sorting by custom attribute broken after upgrading to API 8.6/UI 8.5 

### ISSUE THREAD

**Issue by 3IMOH** [alerta/alerta-webui#480]
We have a custom "AckedBy" attribute configured to display as a column. Prior to upgrading we were able to sort on this column. We are now getting the following error in the UI:

![image](https://user-images.githubusercontent.com/54080089/131359300-5cecd681-95d1-418c-b1a4-b28bd2913cb9.png)

**Comment by satterly** [comment]
Also effects "duration" column.

**Comment by 3IMOH** [comment]
Hi @satterly-
Reopening as the duration column still throws a 400 error when trying to sort. I did verify that custom attributes now sort correctly.
