### ISSUE TITLE
Horizontal scrolling doesn't work

### ISSUE THREAD

**Issue by hayk96** [alerta/alerta-webui#481]
**Issue Summary**
Horizontal scrolling of the rows is not working. I still use version `7.5.4` because it is the last version that supports this feature. It is a helpful feature when you have a long description of the alert.

**Environment**
- OS: Linux
- Deployment: Docker

- Database: MongoDB

- Server config:
  Auth enabled: Yes
  Auth provider: Basic

- web UI version: 8.5.0
- Browser: Chrome

**Comment by 3IMOH** [comment]
I am not sure what it would take to enable scrolling but I believe that there could be some enhancements to the column width configuration and the ability to truncate and add a "..." to long data. I am going to work on an enhancement issue and will post that for comments.

**Comment by hayk96** [comment]
Hi folks. In the version `8.7.0` is already available **Description Text Width** option in the **Settings** (Alert summary settings) tab that allows customizing the length of description text, so I'm closing this issue.
Thanks!
