### ISSUE TITLE
When modify or copy a blackout it stop to works.

### ISSUE THREAD

**Issue by danielelopez1** [alerta/alerta-webui#485]
**Issue Summary**
When modify or copy a blackout it stop to works. 

**Environment**
- OS: Debian GNU/Linux 10 (buster)
- API version: Alerta API 8.5.0
- Deployment: Docker

- Database: PostgreSQL

- Server config:
  Auth enabled? Yes
  Auth provider? Basic
  Customer views? Yes
This is my configuration:

```
DATABASE_URL = 'postgresql://user:password@mydb.com/alerta'
DATABASE_NAME = 'alerta'
BASE_URL='/api'

PLUGINS = [
    "amqp",
    "alerta-mailer"
]

AUTH_REQUIRED = True
SECRET_KEY = '1UgWRmd!XGcExUU*dGIM#4kwsN^oR77'
ADMIN_USERS = ['user1', 'user2']
ADMIN_ROLES = ['admin']
USER_DEFAULT_SCOPES = ['read:alerts','read:customers']
CUSTOMER_VIEWS = True
SIGNUP_ENABLED = False
GUEST_DEFAULT_SCOPES = ['read:alerts']

ALLOWED_ENVIRONMENTS = ['Production', 'Pre-Production', 'Disaster Recovery', 'Development', 'Test']

DEBUG = True
COLOR_MAP = {
    'severity': {
        'security'      : '#0000de',
        'critical'      : '#e45959',
        'major'         : '#e97659',
        'minor'         : '#ffa059',
        'warning'       : '#ffc859',
        'informational' : '#7499ff',
        'debug'         : '#ac47b7',
        'trace'         : '#c7c7c7',
        'indeterminate' : '#97aab3',
        'cleared'       : '#59db8f',
        'normal'        : '#59db8f',
        'ok'            : '#59db8f',
        'unknown'       : '#97aab3'
    }
}


SMTP_HOST='mysmtp.com'
SMTP_PORT='25'
MAIL_FROM='noreply@example.com'

AMQP_TOPIC = "notify"
AMQP_URL = 'postgresql://user:password@mydb.com/alerta'
```

- web UI version: 8.5.0
- CLI version: 8.5.0

**To Reproduce**
1. Create a dummy alert.
2. From UI, go to Blackouts
3. Create blackout, compiling some fields to block the dummy alert and then save it
3. Edit blackout, modify any field and save it
4. Re-send the dummy alert, it wuold not be blocked

The same is hapening if I copy the blackout and make any modification to it (the copied blackout is not working at same)

I din't see any error from console

**Expected behavior**
After edited/copied the blackout the alert had to be blocked

**Additional context**
I'm usign latest docker image: Alerta 8.5.0

**Comment by danielelopez1** [comment]
I used the same time range as the first

**Comment by satterly** [comment]
You're going to have to provide more info then. Please list the exact fields used for both alerts and the exact fields used for each blackout so that I can easily reproduce the issue.

If the info you provide is not enough for me to reproduce the issue I'll be forced to close the issue. Thanks.

**Comment by danielelopez1** [comment]
Here my alert
```
alerta@alerta:/$ date
Fri Nov  5 10:31:33 UTC 2021
alerta@alerta:/$ alerta send -r resource1 -e event1 -E production -s major -S service1 -g group1 -t "some text" -O origin1 --customer customer1
a800666e-35a5-4102-bf8b-1b05cf07a195 (6 duplicates)
alerta@alerta:/$ alerta send -r resource1 -e event1 -E production -s major -S service1 -g group1 -t "some text" -O origin1 --customer customer1
a800666e-35a5-4102-bf8b-1b05cf07a195 (7 duplicates)
alerta@alerta:/$ alerta send -r resource1 -e event1 -E production -s major -S service1 -g group1 -t "some text" -O origin1 --customer customer1
a800666e-35a5-4102-bf8b-1b05cf07a195 (8 duplicates)
alerta@alerta:/$ date
Fri Nov  5 10:34:25 UTC 2021
```

here my blackout
```
alerta@alerta:/$ alerta blackouts
ID                                      P  ENVIRONMENT    SERVICE    RESOURCE    EVENT    GROUP    TAGS    ORIGIN    CUSTOMER    START
    END                  DURATION    STATUS    REMAINING    USER    CREATED              COMMENT
------------------------------------  ---  -------------  ---------  ----------  -------  -------  ------  --------  ----------  -----------------
--  -------------------  ----------  --------  -----------  ------  -------------------  ---------
14a13ac8-5215-4cee-a7e8-6aa2d94622b5    8  production     service1   resource1   event1   group1           origin1   customer1   2021/11/05 09:00:
00  2021/11/05 18:00:00  32400s      active    25902s       pippo   2021/11/05 10:30:21  test
b67baa93-c4b3-4867-b96c-f0cbd3eae0a8    1  production                                                                            2021/11/05 08:30:
00  2021/11/05 18:00:00  34200s      active    25902s       pippo   2021/11/05 10:32:15

```

**Comment by satterly** [comment]
You haven't enabled the "blackout" plugin. Your config needs to look something like this ...

```
PLUGINS = [
    "blackout",
    "amqp",
    "alerta-mailer"
]
```

**Comment by danielelopez1** [comment]
Hello, sorry for long delay. 
You are right, it seems the plugin was not enabled. I thought it was a basic plugin, enabled by default, but now i see it is enabled by default only if i don't specify any plugin at all. 


In meanwhile, i noticed that there is not a feature for recursive blackout.
there is another way an user can sience an alert recursively, or there is a chance you develope this feature?

Thank you for your patience
