### ISSUE TITLE
Problem text color when using black color alarm with normal theme

### ISSUE THREAD

**Issue by oijkn** [alerta/alerta-webui#505]
**Issue Summary**
If I set color alarm to black with normal theme, the text is not readable.
If I set color alarm to white with dark theme, the text is not readable.

**Environment**
- OS: CentOS 7
- API version: 8.6.4
- Deployment: Docker

- Database: Postgres

- Server config:
  Auth enabled: Yes
  Auth provider: Keycloack
  Customer views: Yes

- web UI version: 8.6.1
- CLI version: 8.6.4

**To Reproduce**
1. Set color alarm to black
2. Click on alerts menu

**Expected behavior**
A white text over black color

**Screenshots**
![image](https://user-images.githubusercontent.com/18188407/144435840-6f1d5c1a-70f5-40a9-a8a8-b0ded9ee643e.png)
![image](https://user-images.githubusercontent.com/18188407/144437469-d4c930fe-cc63-4aa6-8260-33359fe1a8f3.png)

**Comment by satterly** [comment]
The previous version (in AngularJS) had the following ... 

        <tr ng-repeat="alert in alerts | filter:filter | orderBy:predicate:reverse | limitTo:alertLimit"
            ng-style="{ 'color':  colors.severity[alert.severity] == 'black' ? 'white' : colors.text, 'background-color': (bulkAlerts.indexOf(alert.id) > -1) ? colors.highlight : colors.severity[alert.severity] || 'silver' }"
            ng-click="click($event,alert);">

https://github.com/alerta/angular-alerta-webui/blob/4d0b6327cd3bcde44df6a3db9ad961a92e080748/app/partials/alert-list.html#L48-L50
