### ISSUE TITLE
Ability to format "copy alert" functionality

### ISSUE THREAD

**Issue by 3IMOH** [alerta/alerta-webui#522]
Currently the "copy alert" button copies all alert data (history, etc). It would be great to have the ability to specify a format so that only specific alert fields will be copied when the button is clicked.

Our use case is people sending questions about an alert in email, slack, etc.

Some sort of config in alertad.conf to control what fields are copied would be ideal.

**Comment by kennhardy** [comment]
https://github.com/alerta/alerta-webui/pull/555 approved together with https://github.com/alerta/alerta/pull/1814. Awaiting for merge.

**Comment by kennhardy** [comment]
This one is also related: https://github.com/alerta/alerta-docs/pull/118/
