### ISSUE TITLE
Question: why Alerta gui shows only 50 users ?

### ISSUE THREAD

**Issue by danielelopez1** [alerta/alerta-webui#528]
Hello all, i have a question. 
I have 86 users signed up in my alerta, but in the gui i can see only 50 of them.
eaven when i try to assign an api key, it don't show me the user available.

how can i show all users from the gui?

I'm using ALERTA 8.7.0 from docker hub on a CENTOS 7 environment.

here my configuration

DATABASE_URL = 'postgresql://user:pass@mydb.com/alerta'
DATABASE_NAME = 'alerta'
BASE_URL='/api'
ALERT_TIMEOUT= 0
DEFAULT_EXPIRED_DELETE_HRS = 0
DEFAULT_INFO_DELETE_HRS = 0
SHELVE_TIMEOUT=1
HISTORY_LIMIT = 1000
HISTORY_ON_VALUE_CHANGE = False
DELETE_INFO_AFTER = 1
PLUGINS = [
    "blackout",
    "normalise",
    "reject"
]

BLACKOUT_DURATION = 3 # time in minutes
NOTIFICATION_BLACKOUT = True
BLACKOUT_ACCEPT = ['normal', 'ok', 'cleared']

#########AUTHENTICATION###########
AUTH_REQUIRED = True
SECRET_KEY = '1UgWRmd!XGcExUU*dGIM#4kwsN^oR42'
ADMIN_USERS = ['admin']
ADMIN_ROLES = ['admin']
USER_DEFAULT_SCOPES = ['read:alerts','read:customers']
CUSTOMER_VIEWS = True
AUTH_PROVIDER = 'basic'
SIGNUP_ENABLED = False
GUEST_DEFAULT_SCOPES = ['read:alerts']

#####################
#      WEB UI       #
#####################

AUTO_REFRESH_INTERVAL= 60000
ALLOWED_ENVIRONMENTS = ['Production', 'Pre-Production', 'Disaster Recovery', 'Development', 'Test', 'UNKNOWN']
COLUMNS = ['severity', 'status', 'lastReceiveTime', 'duplicateCount','customer', 'environment', 'service', 'resource', 'event', 'owner', 'value', 'text']
DEFAULT_FILTER = {'status':'open'}

COLOR_MAP = {
    'severity': {
        'security'      : '#0000de',
        'critical'      : '#e45959',
        'major'         : '#e97659',
        'minor'         : '#ffa059',
        'warning'       : '#ffc859',
        'informational' : '#7499ff',
        'debug'         : '#ac47b7',
        'trace'         : '#c7c7c7',
        'indeterminate' : '#97aab3',
        'cleared'       : '#59db8f',
        'normal'        : '#59db8f',
        'ok'            : '#59db8f',
        'unknown'       : '#97aab3'
    }
}

#########################
#       LOGGING         #
#########################

AUDIT_TRAIL = ['admin', 'write', 'auth']
AUDIT_LOG = True
AUDIT_LOG_JSON = True
LOG_HANDLERS = ['file']
LOG_FILE = '/var/log/alerta/alertad.log'
LOG_MAX_BYTES = 15*1024*1024*1024 # value in byte
LOG_BACKUP_COUNT = 1
LOG_FORMAT = 'json'
LOG_LEVEL = 'INFO'
LOG_METHODS = ['POST', 'PUT', 'DELETE']

**Comment by hasso** [comment]
This is a https://github.com/alerta/alerta/issues/1550. To work around add somethings this into alertad.conf:

```
QUERY_LIMIT = 200
DEFAULT_PAGE_SIZE = QUERY_LIMIT
```

**Comment by danielelopez1** [comment]
thanks for your answer.
this works, but it impact not only users, but according to documentation alerts too: 
"DEFAULT_PAGE_SIZE maximum number of alerts returned in a single query (default is 50 items)".
and according with https://github.com/alerta/alerta/issues/1550 the api key list too.  
any other feture are impacted?
i have almost 100 user now, and alerta refresh every minute, i wish to avoid impact on performace due to heavy requests
Thanks
