### ISSUE TITLE
Recurring blackout

### ISSUE THREAD

**Issue by danielelopez1** [alerta/alerta-webui#529]
**Is your feature request related to a problem? Please describe.**
I noticed that there is not a feature for recurring blackout. For example i wish to suppress some alerts in workhours only every day.

**Describe the solution you'd like**
will be great to have some template I can add to blackout to set a recurring time range. 
i.e. I create the template "workhours" and set it from 08:00 to 18:00 in localtime, from monday to wednesday. then when i create a blackout, i can add this template to my blackout and it will be active in that time.

Even in a more simple way, without the template. 
Just insert the wished week-day(s) and the start time and the end time.
It can act like a crontab, wich activate the blackout at the given time.

**Describe alternatives you've considered**
I know about ack and shelved status, but they are not recurring (for example work hours only or every day from 01:00 to 05:00 etc.)

**Additional context**

An image as example

![immagine](https://user-images.githubusercontent.com/74065429/169524164-0ab78dc4-f16c-409f-97d2-d7bf582ce238.png)

currently, there is another way an user can silence an alert recurringly?

**Comment by kennhardy** [comment]
I do see the use case - but have you considered using the API for setting blackouts instead?

I.E - you could use an actual crontab to do this exactly this by using the provided API?
https://docs.alerta.io/api/reference.html?highlight=blackout#blackout-periods

Another good way to do this would be to use some kind of automation tool further down in the monitoring stack. For example Ansible.

**Comment by danielelopez1** [comment]
I thought about this solution, but having to blackout hundreds of resources, since blackouts don't support regular expressions, I would have to set hundreds that are displayed in the web interface, together with those manually set by users, causing quite a bit of confusion.
I wrote above that it doesn't support regular expressions, based on my experience, but maybe it's just me who didn't understand how to use them.

**Comment by satterly** [comment]
This should be a FAQ because I've had this question a few times now.

There are a few possible solutions. The first is to use an external scheduler to create and delete blackouts. The second, which I prefer, is to create a permanent blackout based on something like a tag or alert attribute and then write a plugin that adds the tag or label based on a schedule.

See this example https://github.com/alerta/alerta-contrib/blob/4ba3682468fdd5308e964dc0097860edf8c7da15/plugins/enhance/alerta_enhance.py#L19-L22

Let me know if you need any more info.

**Comment by danielelopez1** [comment]
sorry for late reply. I see a problem with tags. I'll use the first case (th scheduler which create blackout) as an example, but it is the same if you create the plugin to assign the tag, cause the problem is how the tags themself are managed. 
I create a blackout matching a tag. now I have the blackout working from 11:00 am to 15:00pm. I have an alert, and it appear the first time at 10:00am.  the first problem I see in it, is that at 11:00am it will not be in blackout, cause blackout are not retroactive. 
now, suppose I have an update, at 12:00pm the alert is set in blackout state, and it is fine, is what i expect.
tomorrow, I'll create a new blackout as per schedule, and I'll expect it will works as the first time, cause it is the same.
here I see the second problem. for business reason, I decide the alert had to have a different blackout time, from 02:00 am to 04:00am and it had to not match more the previous blackout. teorically I had to add a new tag and create a new blackout to match the new tag. that is ok, but the previous tag will not go away, cause the tag are cumulative and I have no chance to delete the previously tag (ofcourse i can do it by deletig it from alerta database, but it prevent me to do it automatically)
delete the previous blackout is not an option, cause it is used by other alerts.
